language: python
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
python:
  - 2.7
install:
# Keep setuptools and zc.buildout in sync with buildout.cfg please.
  - python bootstrap-buildout.py --buildout-version=2.5.3 --setuptools-version=27.3.0
  - bin/buildout -Nc travis.cfg buildout:eggs-directory=$HOME/buildout-cache/eggs buildout:download-cache=$HOME/buildout-cache/downloads
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coverage==3.7 coveralls
  - coveralls

notifications:
  email:
    - maurits@vanrees.org
